# Generated by Django 5.2.7 on 2025-10-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.PositiveIntegerField(help_text='A duração precisa ser inserida em minutos.')),
                ('description', models.TextField(help_text='Breve descrição do serviço', max_length=300)),
            ],
        ),
    ]
