# Generated by Django 5.2.7 on 2025-10-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Breve descrição do serviço.', max_length=500),
        ),
    ]
