# Generated by Django 5.2.7 on 2025-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Breve descrição do serviço.'),
        ),
    ]
