# Generated by Django 5.2.7 on 2025-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='A duração precisa ser inserida em minutos.'),
        ),
    ]
