# Generated by Django 5.2.7 on 2025-10-06 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0002_alter_service_description'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='services.service')),
                ('staff', models.ManyToManyField(related_name='appointment', to='staff.staff')),
            ],
        ),
    ]
